language: ruby
sudo: false
rvm: 2.2.0
script: bundle exec rake deploy
env:
  global:
    secure: i6V+YIvAyKrQdvf9Wp59a7a2UxSyW0tR6fvgtdSqb0izr2XFK1Q+gRQFOAo+3C4kag+Y4IxJ89q/BwZ6LHB8NScJuOK4VM2q9Pg/ptNdD523JcY4MmffeG2W4W+D/Si8RAaZXXfPBLVGUnphTkYENe4yaft7I+vrqNyOYCmdVSEwuT1zsGaIMsfIbWZiXet0BFP2IjI3jpvTKtUPB+uYPzfQWk1Ke54gzjJtdcYHpzqDs6ARFuaIRnc6sZBiBdPmesUXKsqDdD7vRdIK6XqfIRHtAZF2savPm8RG0xqgr1qo/L6iUGTEMavo8vxohZp+oFQwy3X4pBTxMdynYMQ2vISDvTkyGV2loVShod+lBf8OHpa5n4tYz/XMOaP5EQ3B7vPkWV7G1QMN0t31RAgl++4L3VHcZX5rb+IQSmSA8t07CAi7envPCybSSQXgHv/druG6j4XFMZn0cuUKljL0DU8MkXVaXF3p+iHgoJvsnG/uzRZH6NaznHFiqlirQCFPs/zub/TSZhBzF4tziyMnpooiVj41xQh1eU0jdPyOSQl7JmpzQy/ZEbyTj/bI3u2UY50b8zxKwC5K2KNO6piFg8FZScKj7FYZQ9mZRRsJPQFDK0KBshnhfsJsF6FLOPinTC8Bu2rtf/Zk/zRFGr+mTq8TxOECgdLBGt6IJpAdy9k=
branches:
  only:
    - source
