aws:
  slug: aws
  name: Amazon
cloud:
  slug: cloud
  name: Cloud
docker:
  slug: docker
  name: Docker
gitlab:
  slug: gitlab
  name: GitLab
java:
  slug: java
  name: Java
spring:
  slug: spring
  name: Spring Framework
terraform:
  slug: terraform
  name: Terraform
graphql:
  slug: graphql
  name: GraphQL
clojure:
  slug: clojure
  name: Clojure
clojurescript:
  slug: clojurescript
  name: Clojure Script
bézier:
  slug: bézier
  name: Bézier
functional:
  slug: functional
  name: Functional
klipse:
  slug: klipse
  name: Klipse
canvas:
  slug: fullstack
  name: Full Stack
canvas:
  slug: security
  name: Security
canvas:
  slug: iot
  name: IoT
canvas:
  slug: microservices
  name: Micro Services
