aws:
  slug: aws
  name: Amazon
cloud:
  slug: cloud
  name: Cloud
docker:
  slug: docker
  name: Docker
gitlab:
  slug: gitlab
  name: GitLab
java:
  slug: java
  name: Java
spring:
  slug: spring
  name: Spring Framework
terraform:
  slug: terraform
  name: Terraform
graphql:
  slug: graphql
  name: GraphQL
