aws:
  slug: aws
  name: Amazon
cloud:
  slug: cloud
  name: Cloud
docker:
  slug: docker
  name: Docker
gitlab:
  slug: gitlab
  name: GitLab
java:
  slug: java
  name: Java
spring:
  slug: spring
  name: Spring Framework
terraform:
  slug: terraform
  name: Terraform
graphql:
  slug: graphql
  name: GraphQL
clojure:
  slug: clojure
  name: Clojure
clojurescript:
  slug: clojurescript
  name: Clojure Script
bezier:
  slug: bezier
  name: Bézier
functional:
  slug: functional
  name: Functional
klipse:
  slug: klipse
  name: Klipse
canvas:
  slug: canvas
  name: Canvas
fullstack:
  slug: fullstack
  name: Full Stack
security:
  slug: security
  name: Security
iot:
  slug: iot
  name: IoT
microservices:
  slug: microservices
  name: Micro Services
aframe:
  slug: aframe
  name: AFrame
serviceworkers:
  slug: serviceworkers
  name: Service Workers
css:
  slug: css
  name: CSS
javascript:
  slug: javascript
  name: JavaScript
ast:
  slug: ast
  name: AST
svg:
  slug: svg
  name: SVG
blockchain:
  slug: blockchain
  name: Blockchain
react:
  slug: react
  name: React
serverless:
  slug: serverless
  name: Serverless
microhack:
  slug: microhack
  name: MicroHack
python:
  slug: python
  name: Python
mac:
  slug: mac
  name: MacOS
brew:
  slug: brew
  name: HomeBrew
git:
  slug: git
  name: Git
rust:
  slug: rust
  name: Rust
